### ISSUE TITLE
FileNotFound error: please provide ./raft/raft-casme_smic.pth

### ISSUE THREAD

**Issue by prashnani** [phflot/dsd_momag#1]
hi @phflot ! Thank you for providing the source code for your project. 

Would you please also provide the RAFT model trained on CASME II? I am unable to run your code for visualizing magnified micro-expressions without it.

**Comment by phflot** [comment]
Hi, thank you for your interest in our code. I am currently preparing the repo for a second motion magnification publication with which we will include the complete training code and a link to the pre-trained files. I'll post the link here soon.

**Comment by phflot** [comment]
Hi @prashnani, the code should now run out of the box and download an appropriate raft model on the fly. For reference, you can get the file also here: https://cloud.hiz-saarland.de/s/McMNXZ5o7xteE6n/download/raft-casme2.pth
